### ISSUE TITLE
Ledger device: Missing critical parameter (0x6800)

### ISSUE THREAD

**Issue by dangell7** [LedgerHQ/app-xrp#18]
If I try to sign the following tx json it fails with `Ledger device: Missing critical parameter (0x6800)`

```
{
    Account: "OMMITED"
    Domain: "OMMITED"
    Fee: "12"
    Flags: 65536
    LastLedgerSequence: 67379294
    Sequence: 67377767
    SetFlag: 8
    SigningPubKey: "OMMITED"
    TickSize: 6
    TransactionType: "AccountSet"
    TransferRate: 1030000000
}
```

If I remove the `Flags` parameter it succeeds in the signature but fails to decode correctly. 

Any Ideas?

**Comment by patriksletmo** [comment]
The XRP app currently requires the flag `tfFullyCanonicalSig` to be set when signing transactions (https://xrpl.org/transaction-common-fields.html#global-flags). It appears that your `Flags` field does not contain it, which would explain why the transaction fails with the error you're seeing.

This flag has been deprecated since its introduction in this app, so it probably makes sense to remove the requirement. Please let me know what you think @RareData @natenichols.

You can find the relevant code here
https://github.com/LedgerHQ/app-xrp/blob/066af6b3c224de8f36451fe647e0396dcc18d1f7/src/xrp/xrp_parse.c#L423-L432

**Comment by RareData** [comment]
I agree, enforcing `tfFullyCanonicalSig` is no longer necessary. Until there is a new firmware version @natenichols, increase your Flags value by the https://xrpl.org/transaction-common-fields.html#global-flags decimal value `2147483648`. For example, if you intend to sign a transaction with `Flags: 65536`, use `Flags: 2147549184` instead.

**Comment by dangell7** [comment]
Thank you guys, I really appreciate the quick feedback. 

This worked to solve the issue in the OP.
